name: FFA
version: '1.0.9'
main: me.kaitp1016.ffa.FFA
api-version: '1.21'
authors: [ kaitp1016 ]
description: ''
website: https://discord.gg/2PGFuasqFM

commands:
  ffa:
    description: Your description
    usage: /<command>
    permission: ffa.commands.ffa

permissions:
  ffa.commands.ffa:
    default: op