name: FFA
version: '1.2.1'
main: me.kaitp1016.ffa.FFA
api-version: '1.21'
authors: [ kaitp1016 ]
description: ''
website: https://discord.gg/2PGFuasqFM

commands:
  ffa:
    description: ffaの管理用コマンド
    usage: /ffa
    permission: ffa.commands.ffa
  spawn:
    description: スポーンにテレポート
    usage: /spapwn
    permission: ffa.commands.spawn
  pay:
    description: ポイントを送る
    usage: /pay
    permission: ffa.commands.pay

permissions:
  ffa.commands.ffa:
    default: op
  ffa.commands.spawn:
    default: true
  ffa.commands.pay:
    default: true